version: '3.3'

services:
  # Banco de dados PostgreSQL
  database:
    image: postgres:15
    container_name: playbox-database-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: playbox
      POSTGRES_USER: playbox_user
      POSTGRES_PASSWORD: playbox_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - playbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U playbox_user -d playbox"]
      timeout: 10s
      retries: 10
      interval: 10s

  # Backend (API)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: playbox-backend-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://playbox_user:playbox_password@database:5432/playbox"
      NODE_ENV: development
      JWT_SECRET: "your-secret-key-here"
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - playbox-network
    command: npm run dev

  # Frontend (React)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: playbox-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - playbox-network
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:

networks:
  playbox-network:
    driver: bridge
