version: '3.3'

services:
  # Backend (API)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: playbox-backend-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - playbox-network
    command: npm run dev

  # Frontend (React)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: playbox-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - playbox-network
    stdin_open: true
    tty: true

networks:
  playbox-network:
    driver: bridge
