version: '3.3'

services:
  # Banco de dados MySQL
  database:
    image: mysql:8.0
    container_name: playbox-database-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: playbox
      MYSQL_USER: playbox_user
      MYSQL_PASSWORD: playbox_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - playbox-network
    command: --default-authentication-plugin=mysql_native_password

  # Backend (API)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: playbox-backend-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://playbox_user:playbox_password@database:3306/playbox"
      NODE_ENV: development
      JWT_SECRET: "your-secret-key-here"
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - playbox-network
    command: npm run dev

  # Frontend (React)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: playbox-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - playbox-network
    stdin_open: true
    tty: true

volumes:
  mysql_data_dev:

networks:
  playbox-network:
    driver: bridge
