name: Deploy Backend no Render

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend no Render
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
